In [10]:
import pandapower as pp
net = pp.create_empty_network()

In [11]:
b_hv = pp.create_bus(net, vn_kv=138, name="HV Bus")
b_mv = pp.create_bus(net, vn_kv=12.47, name="MV Bus")
b_load = pp.create_bus(net, vn_kv=12.47, name="Load Bus")

In [12]:
pp.create_ext_grid(net, bus=b_hv, vm_pu=1.02, name="Utility Source")

np.int64(0)

In [13]:
pp.create_transformer_from_parameters(net, hv_bus=b_hv, lv_bus=b_mv, 
                                      sn_mva=25, vn_hv_kv=138, vn_lv_kv=12.47,
                                      pfe_kw=30, vkr_percent=0.5, vk_percent=8,
                                      i0_percent=0.1,name="Transformer")

np.int64(0)

In [14]:
pp.create_line_from_parameters(net, from_bus=b_mv, to_bus=b_load, length_km=3,
                               r_ohm_per_km=0.3, x_ohm_per_km=0.35, c_nf_per_km=10,
                               max_i_ka=0.4, name="Line")

np.int64(0)

In [15]:
pp.create_load(net, bus=b_load, p_mw=8, q_mvar=3, name="Load")

np.int64(0)

In [16]:
print(net)

This pandapower network includes the following parameter tables:
   - bus (3 elements)
   - load (1 element)
   - ext_grid (1 element)
   - line (1 element)
   - trafo (1 element)

In [17]:
pp.runpp(net)
net.res_bus

      vm_pu  va_degree      p_mw    q_mvar
0  1.020000   0.000000 -8.531135 -3.830427
1  1.006671  -1.474999  0.000000  0.000000
2  0.934702  -3.707839  8.000000  3.000000

In [18]:
import pandas as pd

results = []
for load_mw in [8, 12, 16, 20, 24]:      # sweep the load up
    net.load.loc[0, "p_mw"] = load_mw      #editing values in net elements when they've already been created
    pp.runpp(net)
    v_load = net.res_bus.loc[2, "vm_pu"]   # voltage at the load bus
    results.append({"load_mw": load_mw, "v_load_pu": round(v_load, 3)})

pd.DataFrame(results)

   load_mw  v_load_pu
0        8      0.935
1       12      0.901
2       16      0.861
3       20      0.811
4       24      0.742